//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class ListOfWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListOfWork()
        {
            this.Projects = new HashSet<Project>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int no { get; set; }
        public string job { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        public ICollection<Project> listPros { set; get; }
        public string ListProToString()
        {
            string str = "";

            for (int i = 0; i < this.listPros.Count; i++)
            {
                str += listPros.ToList()[i].procode + " ";
            }
            return str;
        }
    }
}
